### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by MineMooreALT** [l3mpik/slither-feeder-bot#1]
I keep getting this error
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Users\Taj\Desktop\rattlesnake-master\feeder.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
every time i try to run you're files i have ran npm instal in the folder btw

**Comment by sandor111** [comment]
Nub

**Comment by l3mpik** [comment]
Download now all repo, go to main path . Type : npm install
Next: node server
Next: node feeder
Install userscript for tempermonkey

Go to slither.io click Play. Left top corner click red button. : )

**Comment by MineMooreALT** [comment]
Sorry i had the half uploaded version :/

**Comment by l3mpik** [comment]
No problem : ) I today make big update. Soo be patient !

**Comment by anonymousxxx02** [comment]
i am getting this problem
`module.js:327  
    throw err;  
    ^                                                                                                                                                            

Error: Cannot find module 'socket.io-client'  
    at Function.Module._resolveFilename (module.js:325:15)  
    at Function.Module._load (module.js:276:25)  
    at Module.require (module.js:353:17)  
    at require (internal/module.js:12:17)  
    at Object.<anonymous> (/home/ubuntu/workspace/slither-feeder-bot-master/feeder.js:7:16)  
    at Module._compile (module.js:409:26)  
    at Object.Module._extensions..js (module.js:416:10)  
    at Module.load (module.js:343:32)  
    at Function.Module._load (module.js:300:12)  
    at Module.runMain [as _onTimeout](module.js:441:10)  `

**Comment by l3mpik** [comment]
lol ,  type npm install socket.io-client

**Comment by MineMooreALT** [comment]
C:\Users\Taj\Desktop\slither-feeder-bot-master>node server
module.js:341
    throw err;
    ^

Error: Cannot find module 'socket.io'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Taj\Desktop\slither-feeder-bot-master\server.js:5:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

C:\Users\Taj\Desktop\slither-feeder-bot-master>pause
Press any key to continue . . .


Help please

**Comment by anonymousxxx02** [comment]
@l3mpik thanks bro ;)

**Comment by l3mpik** [comment]
omg, u don't see any repeat text? type : npm install socket.io

**Comment by wartoz** [comment]
l3mpik you shouldn't share many people will steal your work now

**Comment by wartoz** [comment]
and it will kill slither.io

**Comment by l3mpik** [comment]
Hmm... I just make this like old Ogar feeder bot. Same idea, for all ... Sorry.

**Comment by MineMooreALT** [comment]
Hey how do i switch into VPS mode

**Comment by l3mpik** [comment]
Use brain.

**Comment by MineMooreALT** [comment]
thanks

**Comment by l3mpik** [comment]
Bro. 1 im very good person and i share this script. 2. U don't read anything. Just read, open userscript ?  Thing little urself.

**Comment by sandor111** [comment]
@l3mpik Hey man do you have skype? Can you please add me: sandor.potjer

**Comment by sandor111** [comment]
Worth mentioning that you need nodejs V8+ atleast for this to work.

**Comment by ghost** [comment]
Umm credits to rattle snake

**Comment by ghost** [comment]
Thx for giving credits 😀

**Comment by quanmanss11** [comment]
wow thanks you

**Comment by quanmanss11** [comment]
"very good person"
