### ISSUE TITLE
I don't know how to run the server

### ISSUE THREAD

**Issue by ZiWaved** [l3mpik/slither-feeder-bot#40]
Error: Cannot find module 'socket.io'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\ \ \slither-feeder-bot-master\server.js:5:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by ZiWaved** [comment]
If i do node server.js

**Comment by ZiWaved** [comment]
Fixed it
